### ISSUE TITLE
400 bad request when importing private chat

### ISSUE THREAD

**Issue by iiiazertyuiopiii** [Ethorbit/Discord-Chat-Importer#4]
Hey,
thanks for your work, I was really interested in transferring contents of a private conversation (MP) to a channel in a server.
I added a bot with admin rights, and started the import command on the bot who gave me the 'Import Confirmation' prompt.

In the exe logs I have this :

Logging in...
Logged in.
Message failed to import. - (The server responded with error 400: BadRequest)
Message failed to import. - (The server responded with error 400: BadRequest)
Message failed to import. - (The server responded with error 400: BadRequest)
Message failed to import. - (The server responded with error 400: BadRequest)
Message failed to import. - (The server responded with error 400: BadRequest)

Do you have any advice on how to debug? I tried with fiddler and wireshark, but I didn't manage to see the http requests made by the exe so I don't know what it's not happy about :(

**Comment by iiiazertyuiopiii** [comment]
Hey, issue is about the author tag
https://discord.com/developers/docs/resources/channel#embed-object-embed-author-structure 
it requires an URL, but in my JSON export it didn't generate an URL, just a relative path on disk

**Comment by Sw33tSavag3** [comment]
Hello, i am experiencing the same issue with error 400. What URL do I need to put where?

**Comment by iiiazertyuiopiii** [comment]
Hey, I just removed the url all together in the code because I didn't need to export attachments
Sorry for the delay
